<?xml version="1.0"?>
<robot name="four_wheel_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_length" value="0.025"/>
  <xacro:property name="wheel_mass" value="0.2"/>
  <xacro:property name="base_length" value="0.4"/>
  <xacro:property name="base_width" value="0.3"/>
  <xacro:property name="base_height" value="0.05"/>
  <xacro:property name="base_mass" value="5.0"/>
  <xacro:include filename="$(find my_ekf)/urdf/sensors.urdf.xacro"/>
  <xacro:include filename="$(find my_ekf)/urdf/setup_sim.gazebo"/>
  <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/platform</robotNamespace>
      </plugin>
  </gazebo>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 0.6 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${base_mass}"/>
      <inertia ixx="${(1/12) * base_mass * (base_width*base_width + base_height*base_height)}" 
               ixy="0.0" ixz="0.0"
               iyy="${(1/12) * base_mass * (base_length*base_length + base_height*base_height)}" 
               iyz="0.0" 
               izz="${(1/12) * base_mass * (base_length*base_length + base_width*base_width)}"/>
    </inertial>
    <gazebo>
      <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <rosDebugLevel>na</rosDebugLevel>
        
        <!-- Topics -->
        <publishWheelTF>false</publishWheelTF>
        <publishTf>true</publishTf>
        <publishOdom>true</publishOdom>
        <odometryTopic>odom</odometryTopic>

        <!-- Robot structure -->
        <leftJoint>rear_left_wheel_joint</leftJoint>
        <rightJoint>rear_right_wheel_joint</rightJoint>
        <wheelSeparation>0.3125</wheelSeparation>
        <wheelDiameter>0.1</wheelDiameter>

        <!-- Coordinate frames -->
        <robotNamespace>/platform</robotNamespace>
        <frameName>odom</frameName>
        <odometryFrame>odom</odometryFrame>
        <robotBaseFrame>base_link</robotBaseFrame>

        <!-- Update rates -->
        <updateRate>50.0</updateRate>
      </plugin>
  </gazebo>
  </link>

  <!-- Define wheels -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <material name="blue">
          <color rgba="0 0 1 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      </collision>
      <inertial>
          <mass value="${wheel_mass}" />
          <inertia ixx="${(2/5) * wheel_mass * (wheel_radius*wheel_radius)}" ixy="0.0" ixz="0.0"
                  iyy="${(2/5) * wheel_mass * (wheel_radius*wheel_radius)}" iyz="0.0"
                  izz="${(2/5) * wheel_mass * (wheel_radius*wheel_radius)}" />
        </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} -0.015" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="10" velocity="10"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>
  </xacro:macro>

  <!-- Instantiate wheels -->
  <xacro:wheel name="front_left_wheel" x="${(base_length-wheel_radius-0.02)/2}" y="${(base_width+wheel_length)/2}"/>
  <xacro:wheel name="front_right_wheel" x="${(base_length-wheel_radius-0.02)/2}" y="${-(base_width+wheel_length)/2}"/>
  <xacro:wheel name="rear_left_wheel" x="${-(base_length-wheel_radius-0.02)/2}" y="${(base_width+wheel_length)/2}"/>
  <xacro:wheel name="rear_right_wheel" x="${-(base_length-wheel_radius-0.02)/2}" y="${-(base_width+wheel_length)/2}"/>

  <!-- Transmissions (assuming left and right wheel drive) -->
  <transmission name="left_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="rear_left_wheel_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="right_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="rear_right_wheel_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
